module.exports = [
  // Progression
  { key: 'LEVEL_1', name: 'Level 1', description: 'Reached Level 1', category: 'Progression', tier: 1, field: 'level', threshold: 1, reward: { card: true } },
  { key: 'LEVEL_5', name: 'Level 5', description: 'Reached Level 5', category: 'Progression', tier: 2, field: 'level', threshold: 5, reward: { card: true } },
  { key: 'LEVEL_10', name: 'Level 10', description: 'Reached Level 10', category: 'Progression', tier: 3, field: 'level', threshold: 10, reward: { card: true, title: { name: 'Rising Talent', slug: 'rising-talent', description: 'Reached Level 10.', gradient: 'linear-gradient(90deg, #f6d365 0%, #fda085 100%)', isAnimated: true } } },
  { key: 'LEVEL_20', name: 'Level 20', description: 'Reached Level 20', category: 'Progression', tier: 4, field: 'level', threshold: 20, reward: { card: true } },
  { key: 'LEVEL_50', name: 'Level 50', description: 'Reached Level 50', category: 'Progression', tier: 5, field: 'level', threshold: 50, reward: { packs: 1 } },
  // Trading
  { key: 'FIRST_TRADE', name: 'First Trade', description: 'Complete your first trade', category: 'Trading', field: 'completedTrades', threshold: 1, reward: { card: true } },
  { key: 'TRADER_I', name: 'Trader I', description: 'Completed 10 trades', category: 'Trading', tier: 1, field: 'completedTrades', threshold: 10, reward: { card: true } },
  { key: 'TRADER_II', name: 'Trader II', description: 'Completed 50 trades', category: 'Trading', tier: 2, field: 'completedTrades', threshold: 50, reward: { card: true } },
  { key: 'TRADER_III', name: 'Trader III', description: 'Completed 100 trades', category: 'Trading', tier: 3, field: 'completedTrades', threshold: 100, reward: { packs: 1, title: { name: 'Trade Baron', slug: 'trade-baron', description: 'Completed 100 trades.', color: '#7bdff2' } } },
  { key: 'MASTER_TRADER', name: 'Master Trader', description: 'Complete 200 trades', category: 'Trading', field: 'completedTrades', threshold: 200, reward: { packs: 1 } },
  // Market
  { key: 'SELLER_I', name: 'Seller I', description: 'Create 10 market listings', category: 'Market', tier: 1, field: 'createdListings', threshold: 10, reward: { card: true } },
  { key: 'SELLER_II', name: 'Seller II', description: 'Create 50 market listings', category: 'Market', tier: 2, field: 'createdListings', threshold: 50, reward: { card: true } },
  { key: 'SELLER_III', name: 'Seller III', description: 'Create 100 market listings', category: 'Market', tier: 3, field: 'createdListings', threshold: 100, reward: { packs: 1 } },
  { key: 'FIRST_SALE', name: 'First Sale', description: 'Sell your first listing', category: 'Market', field: 'completedListings', threshold: 1, reward: { card: true } },
  { key: 'MERCHANT_I', name: 'Merchant I', description: 'Sold 10 cards on the market', category: 'Market', tier: 1, field: 'completedListings', threshold: 10, reward: { card: true } },
  { key: 'MERCHANT_II', name: 'Merchant II', description: 'Sold 50 cards on the market', category: 'Market', tier: 2, field: 'completedListings', threshold: 50, reward: { card: true } },
  { key: 'MERCHANT_III', name: 'Merchant III', description: 'Sold 100 cards on the market', category: 'Market', tier: 3, field: 'completedListings', threshold: 100, reward: { packs: 1, title: { name: 'Market Baron', slug: 'market-baron', description: 'Sold 100 listings.', color: '#5dd39e' } } },
  { key: 'FIRST_PURCHASE', name: 'First Purchase', description: 'Buy your first card from the market', category: 'Market', field: 'completedPurchases', threshold: 1, reward: { card: true } },
  { key: 'BUYER_I', name: 'Buyer I', description: 'Buy 10 cards from listings', category: 'Market', tier: 1, field: 'completedPurchases', threshold: 10, reward: { card: true } },
  { key: 'BUYER_II', name: 'Buyer II', description: 'Buy 50 cards from listings', category: 'Market', tier: 2, field: 'completedPurchases', threshold: 50, reward: { card: true } },
  { key: 'BUYER_III', name: 'Buyer III', description: 'Buy 100 cards from listings', category: 'Market', tier: 3, field: 'completedPurchases', threshold: 100, reward: { packs: 1 } },
  // Packs
  { key: 'FIRST_PACK', name: 'First Pack', description: 'Open your first pack', category: 'Packs', field: 'openedPacks', threshold: 1, reward: { card: true } },
  { key: 'OPENER_I', name: 'Opener I', description: 'Opened 10 packs', category: 'Packs', tier: 1, field: 'openedPacks', threshold: 10, reward: { card: true } },
  { key: 'OPENER_II', name: 'Opener II', description: 'Opened 50 packs', category: 'Packs', tier: 2, field: 'openedPacks', threshold: 50, reward: { card: true } },
  { key: 'OPENER_III', name: 'Opener III', description: 'Opened 100 packs', category: 'Packs', tier: 3, field: 'openedPacks', threshold: 100, reward: { packs: 1 } },
  { key: 'PACK_ADDICT', name: 'Pack Addict', description: 'Open 500 packs', category: 'Packs', field: 'openedPacks', threshold: 500, reward: { packs: 2, title: { name: 'Pack Addict', slug: 'pack-addict', description: 'Opened 500 packs.', gradient: 'linear-gradient(90deg, #00b4d8 0%, #90e0ef 100%)', isAnimated: true } } },
  { key: 'CORE_COLLECTOR_I', name: 'Core Collector I', description: 'Collect 10 unique cards from the Core Pack', category: 'Packs', tier: 1, field: 'cardsFromPack', packName: 'Core Pack', threshold: 10, reward: { card: true } },
  { key: 'CORE_COLLECTOR_II', name: 'Core Collector II', description: 'Collect 20 unique cards from the Core Pack', category: 'Packs', tier: 2, field: 'cardsFromPack', packName: 'Core Pack', threshold: 20, reward: { card: true } },
  { key: 'CORE_COLLECTOR_III', name: 'Core Collector III', description: 'Collect 30 unique cards from the Core Pack', category: 'Packs', tier: 3, field: 'cardsFromPack', packName: 'Core Pack', threshold: 30, reward: { packs: 1, title: { name: 'Core Archivist', slug: 'core-archivist', description: 'Catalogued the Core Pack.', color: '#cdb4db' } } },
  // Collection
  { key: 'FAVORITE_CARD', name: 'Card Fan', description: 'Set a favorite card', category: 'Collection', field: 'favoriteCard', threshold: 1, reward: { card: true } },
  { key: 'MODDED_CARD', name: 'Modifier Collector', description: 'Obtain a card with a modifier', category: 'Collection', field: 'hasModifierCard', threshold: 1, reward: { card: true } },
  { key: 'LEGENDARY_CARD', name: 'Legendary Collector', description: 'Acquire a Legendary or better card', category: 'Collection', field: 'hasLegendaryCard', threshold: 1, reward: { packs: 1 } },
  { key: 'COLLECTOR_I', name: 'Collector I', description: 'Own 10 unique cards', category: 'Collection', tier: 1, field: 'uniqueCards', threshold: 10, reward: { card: true } },
  { key: 'COLLECTOR_II', name: 'Collector II', description: 'Own 50 unique cards', category: 'Collection', tier: 2, field: 'uniqueCards', threshold: 50, reward: { card: true } },
  { key: 'COLLECTOR_III', name: 'Collector III', description: 'Own 100 unique cards', category: 'Collection', tier: 3, field: 'uniqueCards', threshold: 100, reward: { packs: 1, title: { name: 'Vault Keeper', slug: 'vault-keeper', description: 'Owned 100 unique cards.', color: '#ffd166' } } },
  { key: 'FULL_SET', name: 'Full Set Achiever', description: 'Own every rarity of a single card', category: 'Collection', field: 'fullSets', threshold: 1, reward: { packs: 1 } },
  { key: 'MODIFIER_HUNTER', name: 'Modifier Hunter', description: 'Own 10 cards with modifiers', category: 'Collection', field: 'modifierCards', threshold: 10, reward: { card: true } },
  { key: 'RARITY_HUNTER', name: 'Rarity Hunter', description: 'Collect at least one card of every rarity', category: 'Collection', field: 'raritiesOwned', threshold: 10, reward: { packs: 1 } },
  { key: 'SET_MASTER', name: 'Set Master', description: 'Own 10 full card sets', category: 'Collection', field: 'fullSets', threshold: 10, reward: { packs: 2, title: { name: 'Set Master', slug: 'set-master', description: 'Completed 10 full sets.', color: '#f28482' } } },
  { key: 'LEGEND_HOARDER', name: 'Legend Hoarder', description: 'Own 250 unique cards', category: 'Collection', field: 'uniqueCards', threshold: 250, reward: { packs: 2 } },
  { key: 'ELDEN_RING_INITIATE', name: 'Tarnished', description: 'Collect 2 Elden Ring cards', category: 'Collection', field: 'cardsWithTag', tag: 'Elden Ring', threshold: 2, reward: { card: true } },
  { key: 'ELDEN_RING_LOREKEEPER', name: 'Erdtree Scholar', description: 'Collect 4 Elden Ring cards', category: 'Collection', field: 'cardsWithTag', tag: 'Elden Ring', threshold: 4, reward: { packs: 1, title: { name: 'Erdtree Scholar', slug: 'erdtree-scholar', description: 'Keeper of Elden Ring lore.', color: '#adb5bd' } } },
  { key: 'HEIST_CREW', name: 'Heist Crew', description: 'Collect The Best to Ever Do It, Partner In Crime, and One More Heist', category: 'Collection', field: 'ownsCardNames', cardNames: ['The Best to Ever Do It', 'Partner In Crime', 'One More Heist'], threshold: 3, reward: { packs: 1, title: { name: 'Heist Planner', slug: 'heist-planner', description: 'Assemble the heist crew.', gradient: 'linear-gradient(90deg, #f7971e 0%, #ffd200 100%)', isAnimated: true } } },
  { key: 'BEAST_COMPANIONS', name: 'Beast Companions', description: 'Collect Best Boy BOSCO, Hunters Companion, and Siamese Soup', category: 'Collection', field: 'ownsCardNames', cardNames: ['Best Boy BOSCO', 'Hunters Companion', 'Siamese Soup'], threshold: 3, reward: { card: true, title: { name: 'Beastkeeper', slug: 'beastkeeper', description: 'A loyal friend to every companion.', color: '#8ecae6' } } },
  { key: 'NIGHT_CITY_RELICS', name: 'Night City Relics', description: 'Collect Night City Vibes and Silverhand', category: 'Collection', field: 'ownsCardNames', cardNames: ['Night City Vibes', 'Silverhand'], threshold: 2, reward: { packs: 1, title: { name: 'Night Runner', slug: 'night-runner', description: 'Carry the relics of Night City.', gradient: 'linear-gradient(90deg, #6a4c93 0%, #ff6f91 100%)', isAnimated: true } } },
  { key: 'ROYAL_GUARD', name: 'Royal Guard', description: 'Collect The Queen and The Golden Nose', category: 'Collection', field: 'ownsCardNames', cardNames: ['The Queen', 'The Golden Nose'], threshold: 2, reward: { card: true } },
  // Login
  { key: 'FIRST_LOGIN', name: 'First Login', description: 'Login for the first time', category: 'Login', field: 'loginCount', threshold: 1, reward: { card: true } },
  { key: 'LOGIN_I', name: 'Regular I', description: 'Login 10 times', category: 'Login', tier: 1, field: 'loginCount', threshold: 10, reward: { card: true } },
  { key: 'LOGIN_II', name: 'Regular II', description: 'Login 50 times', category: 'Login', tier: 2, field: 'loginCount', threshold: 50, reward: { card: true } },
  { key: 'LOGIN_III', name: 'Regular III', description: 'Login 100 times', category: 'Login', tier: 3, field: 'loginCount', threshold: 100, reward: { packs: 1 } },
  { key: 'DAILY_STREAK', name: 'Daily Streak', description: 'Log in 7 days in a row', category: 'Login', field: 'loginStreak', threshold: 7, reward: { packs: 1 } },
  // Profile
  { key: 'FEATURED_FAN', name: 'Featured Fan', description: 'Feature any card on your profile', category: 'Profile', field: 'featuredCardsCount', threshold: 1, reward: { card: true } },
  { key: 'SHOWCASE_PRO', name: 'Showcase Pro', description: 'Feature four cards at once', category: 'Profile', field: 'featuredCardsCount', threshold: 4, reward: { packs: 1 } },
  // Titles
  { key: 'TITLE_INITIATE', name: 'First Title', description: 'Unlock your first title', category: 'Titles', field: 'titlesUnlocked', threshold: 1, reward: { card: true } },
  { key: 'TITLE_COLLECTOR_I', name: 'Title Collector I', description: 'Unlock 3 titles', category: 'Titles', tier: 1, field: 'titlesUnlocked', threshold: 3, reward: { card: true } },
  { key: 'TITLE_COLLECTOR_II', name: 'Title Collector II', description: 'Unlock 6 titles', category: 'Titles', tier: 2, field: 'titlesUnlocked', threshold: 6, reward: { packs: 1 } },
  { key: 'TITLE_COLLECTOR_III', name: 'Title Collector III', description: 'Unlock 10 titles', category: 'Titles', tier: 3, field: 'titlesUnlocked', threshold: 10, reward: { packs: 2 } },
];
